version: '2'
services:
  fpm:
    build: ./server/PHP7fpm/
    volumes:
      - C:/xampp/htdocs/Pagarme:/var/www/html
      - ./Logs/FPM:/var/log/nginx
    ports:
      - "9000:9000"
    links:
      - mysql

  nginx:
    build: ./server/Nginx/
    volumes:
      - ./server/nginx.conf:/etc/nginx/nginx.conf
      - ./server/app.vhost:/etc/nginx/conf.d/app.vhost
      - ./Logs/Nginx:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - fpm

  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=pagarmeprojeto258456
      - MYSQL_DATABASE=pagarme