version: '2'
services:
  php7:
    restart: 'always'
    container_name: php7
    build: ./server/PHP7
    volumes:
      - .:/application
    links:
      - mysql

  node:
    container_name: node
    build: ./server/Node
    command: ["webpack","--config","/application/public/webpack.config.js"]
    volumes:
      - .:/application

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - .:/application
      - ./server/nginx.conf:/etc/nginx/nginx.conf
      - ./server/app.vhost:/etc/nginx/conf.d/app.vhost
      - ./Logs/Nginx:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - php7

  composer:
    container_name: composer
    restart: 'no'
    image: composer/composer:php7
    command: install
    volumes:
      - .:/app

  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: 'always'
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=pagarmeprojeto258456
      - MYSQL_DATABASE=pagarme
    volumes:
      - .:/application


  mysql_dump:
   container_name: mysql_dump
   build: ./server/MySQL
   restart: 'always'
   links:
    - mysql
